# Generated by Django 2.2 on 2019-04-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190424_1703'),
        ('notifications', '0002_auto_20190424_1833'),
    ]

    operations = [
    ]
